### ISSUE TITLE
希望放出些测试结果

### ISSUE THREAD

**Issue by chekun** [hpxl/nginx-lua-fastdfs-GraphicsMagick#1]

**Comment by hpxl** [comment]
好的，后面会放出。

**Comment by fuyuehua22** [comment]
话说这个需要怎么运行？没有一个说明文档吗？

**Comment by blackkeai** [comment]
我想问下，我部署上之后报错了！！！  restyfastdfs.lua:463: attempt to index local 'res' (a nil value)
说这句为null了，不知道怎么回事！

**Comment by phpboke** [comment]
我和上一样的错误
2017/12/03 00:10:38 [error] 34696#0: *16 lua entry thread aborted: runtime error: /usr/local/nginx/conf/lua/restyfastdfs.lua:463: attempt to index local 'res' (a nil value)
